### ISSUE TITLE
Unit Test failed due to fileExist error 

### ISSUE THREAD

**Issue by geovlazar** [gov-suite/governed-instrument#1]
FIle path not working in the unit test case.
When we try to run the file path directly the same happened in both JSON and even `./giai_test.golden/medigy-evaluation-facets.conf.ts.`
Tried these following methods in the code  and found not working

- [How to check if a file exists in Deno](https://stackoverflow.com/questions/56658114/how-can-one-check-if-a-file-or-directory-exists-using-deno)
- [How can one check if a file or directory exists using Deno?](https://stackoverflow.com/questions/56658114/how-can-one-check-if-a-file-or-directory-exists-using-deno)

Alternatively, we tried the same with another independent Deno installed windows machine ( Not in WSL Debian) with `deno test --unstable --allow-read `but it works fine there with static paths using "/". Also referred Permission based issues with Deno but not getting any errors like that.
Looking for further solutions to solve this by evaluating why the file path not getting correctly in WSL2

**Comment by shah** [comment]
This is fixed.
